export const constantType = {
    GET_NEWS_DATA: "GET_NEWS_DATA",
    GET_NEWS_DATA_SUCCESS: "GET_NEWS_DATA_SUCCESS",

    GET_SEARCH_NEWS_DATA: "GET_SEARCH_NEWS_DATA",
    GET_SEARCH_NEWS_DATA_SUCCESS: "GET_SEARCH_NEWS_DATA_SUCCESS",

    LOADER_SUCCESS_TRUE: "LOADER_SUCCESS_TRUE",
    LOADER_SUCCESS_FALSE: "LOADER_SUCCESS_FALSE"
}